name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4

    - name: pnpm 설치
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: 준비
      run: pnpm i --frozen-lockfile

    - name: 스토리북 서버 시작
      run: pnpm storybook --ci --port 6006 & # 백그라운드로 실행
        
    - name: 스토리북 서버 대기
      run: pnpm dlx wait-on tcp:6006 # 서버가 준비될 때까지 대기
        
    - name: 테스트 실행
      run: pnpm exec playwright install chromium && pnpm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
    
      - name: pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 준비
        run: pnpm i --frozen-lockfile

      - name: 빌드
        run: pnpm build

      - name: gh-pages에 배포
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist    # 빌드된 파일이 있는 디렉토리
          publish_branch: gh-pages


