name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml  # 재사용 워크플로우를 호출

  test:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: 스토리북 서버 시작
        run: pnpm storybook --ci --port 6006 &

      - name: 스토리북 서버 대기
        run: pnpm dlx wait-on tcp:6006

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: 테스트 실행
        run: pnpm test-storybook

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: pnpm 빌드 준비
        # prepare에서 한 단계가 새 환경에선 없으므로 다시 체크아웃, 설치 필요
        uses: ./.github/workflows/prepare.yml

      - name: 빌드
        run: pnpm build

      - name: 배포
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages


